
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async hello(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hello", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tcpConnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tcp_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bleConnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ble_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBattery() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_battery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendString(string: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_string", { string }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type MemoriLayout = 
/**
 * ┌─────────────────┐
 * │                 │
 * │                 │
 * │      Full       │
 * │                 │
 * │                 │
 * └─────────────────┘
 */
{ Full: WidgetId } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │        │        │
 * │  Left  │ Right  │
 * │        │        │
 * │        │        │
 * └────────┴────────┘
 */
{ VSplit: { left: WidgetId; right: WidgetId } } | 
/**
 * ┌─────────────────┐
 * │                 │
 * │       Top       │
 * │                 │
 * ├─────────────────┤
 * │                 │
 * │     Bottom      │
 * │                 │
 * └─────────────────┘
 */
{ HSplit: { top: WidgetId; bottom: WidgetId } } | 
/**
 * ┌──────┬──────────┐
 * │      │          │
 * │      │   Right  │
 * │      │    Top   │
 * │ Left ├──────────┤
 * │      │          │
 * │      │  Right   │
 * │      │  Bottom  │
 * └──────┴──────────┘
 */
{ VSplitWithRightHSplit: { left: WidgetId; right_top: WidgetId; right_bottom: WidgetId } } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │  Top   │  Top   │
 * │  Left  │ Right  │
 * ├────────┴────────┤
 * │                 │
 * │                 │
 * │     Bottom      │
 * └─────────────────┘
 */
{ HSplitWithTopVSplit: { bottom: WidgetId; top_right: WidgetId; top_left: WidgetId } } | 
/**
 * ┌──────────┬──────┐
 * │          │      │
 * │   Left   │      │
 * │    Top   │      │
 * ├──────────┤ Right│
 * │          │      │
 * │   Left   │      │
 * │  Bottom  │      │
 * └──────────┴──────┘
 */
{ VSplitWithLeftHSplit: { left_top: WidgetId; left_bottom: WidgetId; right: WidgetId } } | 
/**
 * ┌─────────────────┐
 * │                 │
 * │                 │
 * │       Top       │
 * │                 │
 * ├────────┬────────┤
 * │        │        │
 * │ Bottom │ Bottom │
 * │  Left  │ Right  │
 * └────────┴────────┘
 */
{ HSplitWithBottomVSplit: { top: WidgetId; bottom_left: WidgetId; bottom_right: WidgetId } } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │  Top   │  Top   │
 * │  Left  │ Right  │
 * ├────────┼────────┤
 * │        │        │
 * │ Bottom │ Bottom │
 * │  Left  │ Right  │
 * └────────┴────────┘
 */
{ Fourths: { top_left: WidgetId; top_right: WidgetId; bottom_left: WidgetId; bottom_right: WidgetId } }
export type WidgetId = number

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
