
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async connectDevice(mode: DeviceMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_device", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectDevice() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDeviceMode() : Promise<Result<DeviceMode | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_device_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isConnected() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_connected") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBattery() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_battery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWidgetKinds() : Promise<Result<[MemoriWidget, MemoriWidget, MemoriWidget, MemoriWidget, MemoriWidget, MemoriWidget], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_widget_kinds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendTwitch(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_twitch", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async flashMemoriState(memoriState: MemoriStateInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("flash_memori_state", { memoriState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendGithub(token: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_github", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendName(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_name", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendTemp(lat: number, lon: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_temp", { lat, lon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendBustime(lat: number, lon: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_bustime", { lat, lon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startOauthServer() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_oauth_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loginWithProvider(provider: string) : Promise<Result<UserInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_with_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testGithub() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_github") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Define a widget by its data
 */
export type Bus = { route: string; prediction: string }
export type Clock = { seconds: number; minutes: number; hours: number }
export type DeviceMode = "RealDevice" | "Simulator"
export type Github = { username: string; repo: string; openIssues: number; openPrs: number; stars: number; notifications: number; commits: [number, number, number, number, number, number, number]; weekday: number }
export type MemoriLayout = 
/**
 * ┌─────────────────┐
 * │                 │
 * │                 │
 * │      Full       │
 * │                 │
 * │                 │
 * └─────────────────┘
 */
{ Full: WidgetId } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │        │        │
 * │  Left  │ Right  │
 * │        │        │
 * │        │        │
 * └────────┴────────┘
 */
{ VSplit: { left: WidgetId; right: WidgetId } } | 
/**
 * ┌─────────────────┐
 * │                 │
 * │       Top       │
 * │                 │
 * ├─────────────────┤
 * │                 │
 * │     Bottom      │
 * │                 │
 * └─────────────────┘
 */
{ HSplit: { top: WidgetId; bottom: WidgetId } } | 
/**
 * ┌──────┬──────────┐
 * │      │          │
 * │      │   Right  │
 * │      │    Top   │
 * │ Left ├──────────┤
 * │      │          │
 * │      │  Right   │
 * │      │  Bottom  │
 * └──────┴──────────┘
 */
{ VSplitWithRightHSplit: { left: WidgetId; rightTop: WidgetId; rightBottom: WidgetId } } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │  Top   │  Top   │
 * │  Left  │ Right  │
 * ├────────┴────────┤
 * │                 │
 * │                 │
 * │     Bottom      │
 * └─────────────────┘
 */
{ HSplitWithTopVSplit: { bottom: WidgetId; topRight: WidgetId; topLeft: WidgetId } } | 
/**
 * ┌──────────┬──────┐
 * │          │      │
 * │   Left   │      │
 * │    Top   │      │
 * ├──────────┤ Right│
 * │          │      │
 * │   Left   │      │
 * │  Bottom  │      │
 * └──────────┴──────┘
 */
{ VSplitWithLeftHSplit: { leftTop: WidgetId; leftBottom: WidgetId; right: WidgetId } } | 
/**
 * ┌─────────────────┐
 * │                 │
 * │                 │
 * │       Top       │
 * │                 │
 * ├────────┬────────┤
 * │        │        │
 * │ Bottom │ Bottom │
 * │  Left  │ Right  │
 * └────────┴────────┘
 */
{ HSplitWithBottomVSplit: { top: WidgetId; bottomLeft: WidgetId; bottomRight: WidgetId } } | 
/**
 * ┌────────┬────────┐
 * │        │        │
 * │  Top   │  Top   │
 * │  Left  │ Right  │
 * ├────────┼────────┤
 * │        │        │
 * │ Bottom │ Bottom │
 * │  Left  │ Right  │
 * └────────┴────────┘
 */
{ Fourths: { topLeft: WidgetId; topRight: WidgetId; bottomLeft: WidgetId; bottomRight: WidgetId } }
export type MemoriStateInput = { activeFrameIdx: number; widgets: MemoriWidget[]; frames: MemoriLayout[]; frameTime: number }
export type MemoriWidget = { id: WidgetId; kind: WidgetKind; remoteUpdateFrequency: UpdateFrequency; localUpdateFrequency: UpdateFrequency }
/**
 * Define a widget by its data
 */
export type Name = { name: string }
/**
 * Define a widget by its data
 */
export type Twitch = { user: string }
export type UpdateFrequency = { Seconds: number } | { Minutes: number } | { Hours: number } | "Never"
export type UserInfo = { id: string; name: string; email: string; avatar: string | null; provider: string; accessToken: string }
/**
 * Define a widget by its data
 */
export type Weather = { temp: string; icon: string }
export type WidgetId = number
export type WidgetKind = { Name: Name } | { Clock: Clock } | { Github: Github } | { Weather: Weather } | { Bus: Bus } | { Twitch: Twitch }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
