# DEFAULT
list:
    just --list

[no-cd]
edit:
    $EDITOR justfile

# dev: sv_dev cvx_dev
dev:
    bun run dev --open

# CHECK
check:
    bunx @biomejs/biome check --write .
    bunx dprint fmt "**/*.{svelte,astro}"
    bunx sv check

# Setup
sv_setup NAME="svelte-project":
    bunx sv create {{ NAME }} --template minimal --types ts --install bun --no-add-ons
    # install add-ons and dependencies
    bunx sv add -C {{ NAME }} devtools-json mcp sveltekit-adapter tailwindcss playwright
    cd {{ NAME }} && bun add -D typescript-svelte-plugin @types/node @biomejs/biome dprint @lucide/svelte phosphor-svelte && bun add runed neverthrow
