// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


const ARGS_MAP = { '':'{"connect":[],"get_battery":[],"hello":["name"],"send_string":["string"]}' }
export type Router = { "": {connect: () => Promise<null>, 
get_battery: () => Promise<number>, 
hello: (name: string) => Promise<string>, 
send_string: (string: string) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
